resume_analysis_task:
  description: >
    Analyze the uploaded resume to extract key details such as full name, contact information,
    work experience, education, technical and soft skills, certifications, and other relevant highlights.
  expected_output: >
    A structured summary (as a list or key-value pairs) of the extracted information from the resume.
    Ensure all key sections are represented with relevant data.
  agent: resume_analyst
  output_file: output/analyst_report.md

job_scraping_task:
  description: >
    Based on the extracted resume data, identify 5–10 job listings that best match the candidate's profile.
    For demo purposes, use mocked job descriptions with realistic titles, companies, and required skills.
  expected_output: >
    A list of job postings, each including:
    - Job title
    - Company name
    - Required skills
    - Short job description
    - Mock location and salary info
  agent: job_scraper
  output_file: output/job_scraping_report.md


job_matching_task:
  description: >
    Using the candidate’s resume and the list of job postings, calculate a match score (0–100)
    for each job. Base it on how well the candidate’s skills, experience, and background
    align with the job requirements. Include a brief explanation for each score.
  expected_output: >
    A list of jobs with:
    - Match score
    - Summary of matched and missing criteria
    - Short rationale for the score
  agent: matchmaker
  output_file: output/job_matching_report.md

resume_advising_task:
  description: >
    Review the candidate’s resume and job match scores. Provide clear, actionable suggestions
    to improve the resume in terms of content, formatting, and alignment with the desired roles.
    Focus on areas like missing skills, unclear role descriptions, or outdated formats.
  expected_output: >
    A list of improvement suggestions for the resume, prioritized by impact.
    Include tips for tailoring it to better fit the job market.
  agent: advisor
  output_file: output/resume_advising_report.md
